Repository TR1LL1ON/TR1LL1ON_BE, pull requests merged in 2023-12, with the labels that each got.

#92 Refactor: 숙소 전체 조회 리팩토링
  src/main/java/com/ybe/tr1ll1on/Tr1ll1onApplication.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/dto/request/AccommodationRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommodationServiceImpl.java
Labels: 💡 Refactor

#100 Feat, Refactor: open api 수정
  README.md
  src/main/java/com/ybe/tr1ll1on/AppStartupRunner.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Accommodation.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/AccommodationFacility.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Category.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/OrderItem.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/Orders.java
  src/main/java/com/ybe/tr1ll1on/domain/order/repository/OrderRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductSummaryListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/Product.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/ProductFacility.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ProductReviewListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ProductReviewResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/UserReviewListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/UserReviewResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/model/Review.java
  src/main/java/com/ybe/tr1ll1on/domain/review/repository/ReviewRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/UserController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/User.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/UserFacility.java
  src/main/java/com/ybe/tr1ll1on/domain/user/repository/UserRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
  src/main/java/com/ybe/tr1ll1on/global/constants/ApiConstants.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
  src/test/java/com/ybe/tr1ll1on/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceTest.java
Labels: 🔨 Feat, 💡 Refactor

#104 Feat, Refactor : 리뷰 기능 추가 및 수정
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/OrderItem.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/exception/ReviewExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/global/common/ReviewStatus.java
Labels: 🔨 Feat, 💡 Refactor

#106 Feat: 체크아웃 이후 리뷰작성 활성화 기능 개발
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/global/common/ReviewStatus.java
Labels: 🔨 Feat

#112 Feat: 리뷰 조회 페이지네이션 기능 개발
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/Product.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/model/Review.java
  src/main/java/com/ybe/tr1ll1on/domain/review/repository/ReviewRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/global/common/ReviewPeriod.java
  src/main/java/com/ybe/tr1ll1on/global/constants/ReviewConstants.java
  src/test/java/com/ybe/tr1ll1on/domain/product/controller/ProductControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceTest.java
Labels: 🔨 Feat

#113 Feat: 특정 객실 리뷰 조회 기능 개발
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ProductAllReviewResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ProductReviewResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/repository/ReviewRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
Labels: 🔨 Feat

#116 Refactor: auth refactor
  src/main/java/com/ybe/tr1ll1on/domain/order/repository/OrderRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/exception/ReviewExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/review/repository/ReviewRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/AuthController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/UserController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/LoginResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
  src/main/java/com/ybe/tr1ll1on/global/constants/AuthConstants.java
  src/main/java/com/ybe/tr1ll1on/security/config/JwtSecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/constants/JwtConstants.java
  src/main/java/com/ybe/tr1ll1on/security/dto/TokenInfo.java
  src/main/java/com/ybe/tr1ll1on/security/exception/InvalidTokenException.java
  src/main/java/com/ybe/tr1ll1on/security/exception/SecurityException.java
  src/main/java/com/ybe/tr1ll1on/security/exception/UserNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtFilter.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
  src/main/java/com/ybe/tr1ll1on/security/model/PrincipalDetails.java
  src/main/java/com/ybe/tr1ll1on/security/model/UserPrincipal.java
  src/main/java/com/ybe/tr1ll1on/security/service/CustomUserDetailsService.java
  src/main/java/com/ybe/tr1ll1on/security/service/PrincipalDetailsService.java
  src/main/java/com/ybe/tr1ll1on/security/util/SecurityUtil.java
  src/main/java/com/ybe/tr1ll1on/security/util/SecurityUtilImpl.java
  src/main/java/com/ybe/tr1ll1on/security/util/SecurityUtilProvider.java
Labels: 💡 Refactor

#115 Refactor: 리뷰 및 마이페이지 제출 전 최종 리팩토링
  src/main/java/com/ybe/tr1ll1on/domain/order/repository/OrderRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/exception/ReviewExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/review/repository/ReviewRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewService.java
  src/main/java/com/ybe/tr1ll1on/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/UserController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
Labels: 💡 Refactor

#117 Feat: 평점 소숫점 한자리까지
  README.md
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommodationServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
Labels: 🔨 Feat

#119 Feat: OAuth2.0 소셜 로그인 기능 구현
  README.md
  build.gradle
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/Cart.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/User.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
  src/main/java/com/ybe/tr1ll1on/security/model/PrincipalDetails.java
  src/main/java/com/ybe/tr1ll1on/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/ybe/tr1ll1on/security/oauth/OAuth2Attribute.java
  src/main/java/com/ybe/tr1ll1on/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/ybe/tr1ll1on/security/service/PrincipalDetailsService.java
  src/main/resources/application.yml
Labels: 🔨 Feat
