Repository TR1LL1ON/TR1LL1ON_BE, pull requests merged in 2023-11, with the labels that each got.

#16 Init : 데이터베이스 초기화 작업
  build.gradle
  src/main/java/com/ybe/tr1ll1on/AppStartupRunner.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/dto/AccommodationResponseDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Accommodation.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Category.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/repository/AccommodationCategoryRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/repository/CategoryRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommdationService.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommodationService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductFacilityRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductImageRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/global/constants/ApiConstants.java
  src/main/resources/application.yml
Labels: ⚒️ Fix, 🌝 Init

#18 Feat : Exception 처리 기능
  src/main/java/com/ybe/tr1ll1on/global/exception/Exception.java
  src/main/java/com/ybe/tr1ll1on/global/exception/ExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/global/exception/ExceptionResponseDTO.java
  src/main/java/com/ybe/tr1ll1on/global/exception/TrillionException.java
  src/main/java/com/ybe/tr1ll1on/global/exception/TrillionExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/global/exception/TrillionExceptionHandler.java
Labels: 🔨 Feat, ⚒️ Fix, 🌝 Init

#23 Feat : 숙소 상세 조회 및 객실 상세 조회 기능
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/ProductDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/product/error/ProductError.java
  src/main/java/com/ybe/tr1ll1on/domain/product/exception/ProductException.java
  src/main/java/com/ybe/tr1ll1on/domain/product/exception/ProductExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/Product.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductInfoPerNightRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/request/AccommodationRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/AccommodationFacilityResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/AccommodationImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/ProductFacilityResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/ProductImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/response/ProductResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/global/common/AreaCode.java
  src/main/java/com/ybe/tr1ll1on/global/date/exception/InValidDateException.java
  src/main/java/com/ybe/tr1ll1on/global/date/exception/InValidDateExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/global/date/utill/DateUtil.java
  src/test/java/com/ybe/tr1ll1on/domain/product/controller/ProductControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceTest.java
Labels: 🔨 Feat, ⛑️ Test

#27 Feature/#19 init cart
  build.gradle
  src/main/java/com/ybe/tr1ll1on/domain/cart/controller/CartController.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/AddCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/AddCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/CartDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/CartDto.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/CartItemDto.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/GetCartRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/GetCartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/RemoveCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/RemoveCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/CartError.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/CartIdNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/CartIdNotFoundExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/ProductNotExistException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/ProductNotExsitExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/UserAlreadyHasCartException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/UserAlreadyHasCartExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/UserNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/error/UserNotFoundExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/Cart.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/CartItem.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/repository/CartItemRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/repository/CartRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartService.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/User.java
  src/main/java/com/ybe/tr1ll1on/domain/user/repository/UserRepository.java
  src/test/java/com/ybe/tr1ll1on/domain/cart/controller/CartControllerTest.java
  src/test/java/com/ybe/tr1ll1on/http/cart/AddCarItemHTTP.http
  src/test/java/com/ybe/tr1ll1on/http/cart/DeleteCartItemHTTP.http
  src/test/java/com/ybe/tr1ll1on/http/cart/GetllCartItemsHTTP.http
Labels: 🔨 Feat

#25 Feat: 숙소 전체 조회 기능
  .gitignore
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/dto/AccommodationRequestDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/dto/AccommodationResponseDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/error/InvalidDateException.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/error/InvalidDateExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/AccommodationImage.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/repository/AccommodationMapper.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommodationService.java
  src/main/java/com/ybe/tr1ll1on/global/config/MybatisConfig.java
  src/main/resources/mapper/AccommodationMapper.xml
Labels: 🔨 Feat

#21 Feat: Spring Security 구현
  build.gradle
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/Cart.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/repository/CartRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/AuthController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/UserController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/UserDTO.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/request/LoginRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/LoginResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/SignUpResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/error/UserError.java
  src/main/java/com/ybe/tr1ll1on/domain/user/exception/EmailAlreadyExistsException.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/User.java
  src/main/java/com/ybe/tr1ll1on/domain/user/model/UserFacility.java
  src/main/java/com/ybe/tr1ll1on/domain/user/repository/UserRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
  src/main/java/com/ybe/tr1ll1on/global/exception/TrillionExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/global/security/Principal.java
  src/main/java/com/ybe/tr1ll1on/security/common/Authority.java
  src/main/java/com/ybe/tr1ll1on/security/config/JwtSecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/constants/JwtConstants.java
  src/main/java/com/ybe/tr1ll1on/security/dto/TokenDto.java
  src/main/java/com/ybe/tr1ll1on/security/exception/InvalidTokenException.java
  src/main/java/com/ybe/tr1ll1on/security/exception/NotTokenException.java
  src/main/java/com/ybe/tr1ll1on/security/exception/UserNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtFilter.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
  src/main/java/com/ybe/tr1ll1on/security/model/UserPrincipal.java
  src/main/java/com/ybe/tr1ll1on/security/service/CustomUserDetailsService.java
  src/main/java/com/ybe/tr1ll1on/security/util/SecurityUtil.java
Labels: 🔨 Feat

#36 Feature: 주문하기 API 개발 및 마이페이지 수정
  src/main/java/com/ybe/tr1ll1on/domain/order/controller/OrderController.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/exception/OrderException.java
  src/main/java/com/ybe/tr1ll1on/domain/order/exception/OrderExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/OrderItem.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/Orders.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/response/OrderResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/request/AccommodationRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationFacilityResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductFacilityResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/ProductInfoPerNight.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/exception/InValidUserException.java
  src/main/java/com/ybe/tr1ll1on/domain/user/exception/InValidUserExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/UserService.java
  src/test/java/com/ybe/tr1ll1on/domain/product/controller/ProductControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/product/repository/ProductInfoPerNightRepositoryTest.java
  src/test/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceTest.java
Labels: 🔨 Feat, ⚒️ Fix

#38 Feature/#32 cart version2
  src/main/java/com/ybe/tr1ll1on/domain/cart/controller/CartController.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/AddCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/CartDto.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/CartItemDto.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/GetCartRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/GetCartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/RemoveCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/RemoveCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/request/AddCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/request/CartRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/AddCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/CartItem.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartService.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartServiceImpl.java
  src/test/java/com/ybe/tr1ll1on/domain/cart/controller/CartControllerTest.java
Labels: 🔨 Feat

#49 Feat : 장바구니 예외 패키지 exception으로 변경 + 조회 시 객실image도 추가함
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/CartIdNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/CartIdNotFoundExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/CartItemIdNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/CartItemIdNotFoundExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/ProductNotExistException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/ProductNotExsitExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/UserAlreadyHasCartException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/UserAlreadyHasCartExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/UserNotFoundException.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/exception/UserNotFoundExceptionCode.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/model/CartItem.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartServiceImpl.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/model/Product.java
Labels: 🔨 Feat

#56 Main 머지
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
Labels: 👐 release

#55 Update README.md
  README.md
Labels: 📝 Docs

#58 Feat, Fix : 숙소 요약 정보 조회 api 개발, 주문하기 api 개발 수정 - 가격 처리
  README.md
  src/main/java/com/ybe/tr1ll1on/Tr1ll1onApplication.java
  src/main/java/com/ybe/tr1ll1on/domain/order/model/Orders.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/request/AccommodationRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductSummaryListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/AuthController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/LoginResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/service/AuthService.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
Labels: 🔨 Feat, ⚒️ Fix

#59 Develop
  src/main/java/com/ybe/tr1ll1on/domain/order/model/Orders.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/request/OrderRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/request/AccommodationRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductSummaryListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
Labels: 👐 release

#61 Test : CartControllerTest 추가
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/service/CartServiceImpl.java
  src/test/java/com/ybe/tr1ll1on/domain/cart/controller/CartControllerTest.java
Labels: ⛑️ Test

#66 Fix: 마이페이지 전체 조회 수정
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageListResponse.java
Labels: 🔨 Feat

#64 Chore: swagger 세팅
  build.gradle
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/ybe/tr1ll1on/global/config/OpenApiConfig.java
  src/main/java/com/ybe/tr1ll1on/security/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/ybe/tr1ll1on/domain/product/controller/ProductControllerTest.java
Labels: 📌 Chore

#68 Feature/#62 cart swagger
  src/main/java/com/ybe/tr1ll1on/domain/cart/controller/CartController.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/request/AddCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/AddCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/global/config/OpenApiConfig.java
Labels: 📝 Docs

#76 Refactor : 객실 당 리뷰 전체 조회 및 패치 조인 설정
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
Labels: 🔨 Feat, 💡 Refactor, ⚒️ Fix

#77 release : 리뷰 수정안 배포
  src/main/java/com/ybe/tr1ll1on/domain/cart/controller/CartController.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/request/AddCartItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/AddCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductInfoPerNightRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/repository/ProductRepository.java
  src/main/java/com/ybe/tr1ll1on/domain/product/service/ProductService.java
  src/main/java/com/ybe/tr1ll1on/global/config/OpenApiConfig.java
  src/main/java/com/ybe/tr1ll1on/security/jwt/JwtTokenProvider.java
Labels: 👐 release

#72 Docs : 스웨거 문서작업 일부 적용
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Accommodation.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/controller/CartController.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/AddCartItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/cart/dto/response/CartResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/controller/OrderController.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/request/OrderItemRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/request/OrderRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/response/OrderItemResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/dto/response/OrderResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/order/service/OrderService.java
  src/main/java/com/ybe/tr1ll1on/domain/product/controller/ProductController.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/AccommodationImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductImageResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/product/dto/response/ProductSummaryListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/controller/ReviewController.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ProductReviewListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewCreateResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewDeleteResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/ReviewUpdateResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/review/dto/response/UserReviewListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/AuthController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/controller/UserController.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/request/LoginRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/LoginResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageDetailResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/MyPageListResponse.java
  src/main/java/com/ybe/tr1ll1on/domain/user/dto/response/SignUpResponse.java
Labels: 📝 Docs

#83 Feature/#82 products test
  src/main/java/com/ybe/tr1ll1on/domain/accommodation/model/Category.java
  src/test/java/com/ybe/tr1ll1on/domain/product/controller/ProductControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/product/service/ProductServiceTest.java
Labels: ⛑️ Test

#85 Test: 숙소 조회 테스트 코드 작성
  src/test/java/com/ybe/tr1ll1on/domain/accommodation/controller/AccommodationControllerTest.java
  src/test/java/com/ybe/tr1ll1on/domain/accommodation/service/AccommodationServiceTest.java
Labels: ⛑️ Test
